name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check for `divincenzo_criteria_lab-2.ipynb`
      id: check-for-divincenzo_criteria_lab-2-ipynb
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check for `divincenzo_criteria_lab-2.ipynb`
        setup-command: ''
        command: test -f divincenzo_criteria_lab-2.ipynb
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-FOR-DIVINCENZO_CRITERIA_LAB-2-IPYNB_RESULTS: "${{steps.check-for-divincenzo_criteria_lab-2-ipynb.outputs.result}}"
      with:
        runners: check-for-divincenzo_criteria_lab-2-ipynb
